version: '3'
services:
  app:
    build: .
    environment:
      - RAILS_ENV=development
      - DATABASE_USERNAME=mysql
      - DATABASE_PASSWORD=root
      - DATABASE_URL=mysql2://root:root@mysql:3306
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    ports:
      - "3000:3000"
    volumes:
      - .:/date-adjuster
      - vendor-bunlde:/date-adjuster/vendor/bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Japan

volumes:
  mysql-data:
    driver: local
  vendor-bunlde:
    driver: local
